version: 2

project_name: lumencast

before:
  hooks:
    - go mod tidy

builds:
  - id: lumencast
    main: ./cmd/lumencast
    binary: lumencast
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: lumencast
    name_template: >-
      lumencast_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - NOTICE
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^test:"

release:
  draft: false
  prerelease: auto
